(function () {
  window.CINAZES_FONT_FAMILIES = [
    {
      name: "AA_Noon",
      slug: "aa-noon",
      description: "AA_Noon Regular specimen",
      detailUrl: "/fonts/aa-noon/",
      licenseSubject: "Лицензия AA_Noon",
      styles: [
        {
          slug: "regular",
          name: "Regular",
          fontFamily: "Etude",
          className: "font-specimen--regular",
          detailClassName: "font-detail-specimen--regular",
          fontFile: "/public/fonts/etude/Etude-Regular.woff2",
          trialFile: "/public/fonts/etude/Etude-Regular.woff2",
          previewText: "AA_Noon",
          tracking: -0.02,
          leading: 0.88,
          size: 220,
        },
      ],
    },
    {
      name: "Triptih",
      slug: "triptih",
      description: "Triptih specimen",
      detailUrl: "/fonts/triptih/",
      licenseSubject: "Лицензия Triptih",
      styles: [
        {
          slug: "fill",
          name: "Fill",
          fontFamily: "Triptih Fill",
          className: "font-specimen--triptih-fill",
          detailClassName: "font-detail-specimen--fill",
          fontFile: "/public/fonts/triptih/Triptih-Fill.otf",
          trialFile: "/public/fonts/triptih/Triptih-Fill.otf",
          previewText: "Triptih",
          tracking: -0.01,
          leading: 0.9,
          size: 220,
        },
        {
          slug: "parth",
          name: "Parth",
          fontFamily: "Triptih Parth",
          className: "font-specimen--triptih-parth",
          detailClassName: "font-detail-specimen--parth",
          fontFile: "/public/fonts/triptih/Triptih-Parth.otf",
          trialFile: "/public/fonts/triptih/Triptih-Parth.otf",
          previewText: "Triptih",
          tracking: -0.01,
          leading: 0.9,
          size: 220,
        },
        {
          slug: "stroke",
          name: "Stroke",
          fontFamily: "Triptih Stroke",
          className: "font-specimen--triptih-stroke",
          detailClassName: "font-detail-specimen--stroke",
          fontFile: "/public/fonts/triptih/Triptih-Stroke.otf",
          trialFile: "/public/fonts/triptih/Triptih-Stroke.otf",
          previewText: "Triptih",
          tracking: -0.01,
          leading: 0.9,
          size: 220,
        },
      ],
    },
  ];
})();
